import React, { useState, useEffect } from 'react';
import { Database, Search, RefreshCw, X, Download } from 'lucide-react';
import EventTable from '../components/EventTable';
import { apiService } from '../services/api';
import { exportEventsToCSV } from '../utils/csvExporter';

export default function Events({ onSelectEvent }) {
  const [events, setEvents] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);

  // Filters
  const [search, setSearch] = useState('');
  const [selectedSource, setSelectedSource] = useState('');
  const [selectedSeverity, setSelectedSeverity] = useState('');

  const fetchEvents = async () => {
    setLoading(true);
    const params = {};
    if (search) params.search = search;
    if (selectedSource) params.source = selectedSource;
    if (selectedSeverity) params.severity = selectedSeverity;

    const res = await apiService.getEvents(params);
    setEvents(res.events || []);
    setTotal(res.total || 0);
    setLoading(false);
  };

  useEffect(() => {
    fetchEvents();
  }, [selectedSource, selectedSeverity]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    fetchEvents();
  };

  const handleClearFilters = () => {
    setSearch('');
    setSelectedSource('');
    setSelectedSeverity('');
  };

  const handleExportCSV = () => {
    exportEventsToCSV(events, `ulpf_events_export_${new Date().toISOString().slice(0, 10)}.csv`);
  };

  return (
    <div className="space-y-6">
      
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Database className="w-5 h-5 text-blue-400" />
            Normalized Events Search & Archive
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Search across unified normalized log records generated by the ULPF pre-processing pipeline.
          </p>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-auto">
          {/* Export CSV Button */}
          <button
            onClick={handleExportCSV}
            disabled={events.length === 0}
            className={`inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-semibold text-white transition-all shadow-sm ${
              events.length === 0
                ? 'bg-slate-800 text-slate-500 border border-slate-700 cursor-not-allowed'
                : 'bg-emerald-600 hover:bg-emerald-500 shadow-emerald-600/30'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
            Export CSV ({events.length})
          </button>

          {/* Refresh Stream Button */}
          <button
            onClick={fetchEvents}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-slate-900 border border-slate-800 hover:bg-slate-800 rounded-lg text-xs font-semibold text-slate-300 shadow-sm transition-colors"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* Filter Controls */}
      <div className="bg-slate-900/80 p-4 rounded-xl border border-slate-800 shadow-sm space-y-3">
        <form onSubmit={handleSearchSubmit} className="flex flex-col md:flex-row gap-3">
          {/* Search Box */}
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-3" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by Event ID, Username (admin), Source IP (192.168.1.10), Event Type..."
              className="w-full pl-9 pr-4 py-2 text-xs border border-slate-800 rounded-lg bg-slate-950 text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          {/* Source Dropdown */}
          <select
            value={selectedSource}
            onChange={(e) => setSelectedSource(e.target.value)}
            className="px-3 py-2 text-xs border border-slate-800 rounded-lg bg-slate-950 text-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500 font-medium"
          >
            <option value="">All Sources</option>
            <option value="Linux">Linux</option>
            <option value="Windows">Windows</option>
            <option value="Firewall">Firewall</option>
            <option value="Application">Application</option>
          </select>

          {/* Severity Dropdown */}
          <select
            value={selectedSeverity}
            onChange={(e) => setSelectedSeverity(e.target.value)}
            className="px-3 py-2 text-xs border border-slate-800 rounded-lg bg-slate-950 text-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500 font-medium"
          >
            <option value="">All Severities</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>

          {/* Search Action */}
          <button
            type="submit"
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-semibold shadow-sm"
          >
            Search
          </button>
        </form>

        {/* Active Filters Summary */}
        {(search || selectedSource || selectedSeverity) && (
          <div className="flex items-center gap-2 text-xs pt-1 border-t border-slate-800">
            <span className="text-slate-400 font-medium">Active Filters:</span>
            {search && <span className="bg-blue-950 text-blue-400 border border-blue-800 px-2 py-0.5 rounded font-mono">"{search}"</span>}
            {selectedSource && <span className="bg-indigo-950 text-indigo-400 border border-indigo-800 px-2 py-0.5 rounded font-medium">Source: {selectedSource}</span>}
            {selectedSeverity && <span className="bg-red-950 text-red-400 border border-red-800 px-2 py-0.5 rounded font-medium">Severity: {selectedSeverity}</span>}
            <button
              onClick={handleClearFilters}
              className="text-slate-400 hover:text-slate-200 ml-auto flex items-center gap-1 font-medium"
            >
              <X className="w-3.5 h-3.5" /> Clear Filters
            </button>
          </div>
        )}
      </div>

      {/* Events Table Container */}
      <div className="space-y-2">
        <div className="flex items-center justify-between px-1">
          <span className="text-xs font-semibold text-slate-400">
            Showing {events.length} of {total} Normalized Event Records
          </span>
        </div>

        <EventTable events={events} onSelectEvent={onSelectEvent} />
      </div>

    </div>
  );
}
